### ISSUE TITLE
Style: index.css - Good first issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#10]
### ATTENTION: CSS skills only for this task =)

> Find a suitable pallet for this project, along with good fonts.

---

- [x] The style will be applied at the moment in the `index.css` file.
- [x] It should apply to the background color
- [ ] It should apply to the font-family
- [x] Its okay to link fonts from fonts google to the `index.html`
- [ ] Please, also add the pallet (as a comment) in the `index.css`, such as primary, secondary colors, muted, etc...

---

If you're willing to help, please comment below to be assigned to this task. Also, read the contributing.md file and and open PRs to the development branch.

Thank you and happy collabing!
=)

**Comment by Lunaris282** [comment]
Hi, give me this task.
I'll try to help.
:))

**Comment by Medic1111** [comment]
You have been assigned =)

**Comment by Lunaris282** [comment]
Hi, 
I have a problem when push  the branch:
remote: Permission to Medic1111/FINALLY-SEEN.git denied to Lunaris282.
fatal: unable to access 'https://github.com/Medic1111/FINALLY-SEEN/': The requested URL returned error: 403.

Can you help, I'm a newbie. Thanks :))

**Comment by Medic1111** [comment]
Hey…. Please make sure you push YOUR new branch. Example: git push origin
yourBranch (if it was a clone)

**Comment by Medic1111** [comment]
PERFECT... I see you have your Branch and its ready to contribute... 
In your repo, Click on `code`, `branches`, select yours, and click on the right, contribute!
You're opening a PR to DEVELOPMENT branch

**Comment by Lunaris282** [comment]
Hey, I completed this issue and made a pull request to merge into the DEVELOPMENT branch as requested. 
I hope this helps.
Thank you.
:>

**Comment by Medic1111** [comment]
`[Lunaris282](https://github.com/Lunaris282) wants to merge 1 commit into [Medic1111:main](https://github.com/Medic1111/FINALLY-SEEN) from [Lunaris282:nguyenLuan](https://github.com/Lunaris282/FINALLY-SEEN/tree/nguyenLuan)` 

The PR is to main... Can you please close this PR and switch the base to development? 
ALMOST THERE! =)
