### ISSUE TITLE
New Component: Wrapper file structure- Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#12]
### ATTENTION: No coding knowledge needed.
> The main section of the application will be always nested inside a wrapper. The initial steps to it will be creating the directory and files needed for it.

---

- [ ] Inside components folder found in client/src, create a new directory called `Wrapper`
- [ ] In that directory, create two files: `Wrapper.tsx`, `Wrapper.module.css`
- [ ] In the `Wrapper.tsx` import `classes` from the `Wrapper.module.css`

> hint: Check other components to see syntaxt for importing that module

---

If willing to contribute, please comment below to be assigned this task. Read the contributing.md and open PRs to the development branch. 

Thank you, and happy collabing!

**Comment by priya1011** [comment]
I would like to work on it. Please aasign.

**Comment by Medic1111** [comment]
All yours =)
Thank you

**Comment by priya1011** [comment]
> All yours =) Thank you

Thanks!!

**Comment by Medic1111** [comment]
MERGED. Thank you for your help!!!
