### ISSUE TITLE
New Component: Wrapper TSX or JSX- Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#15]
> With the file structure created, its time to add some TSX (if not familiar with typescript, feel free to submit the solution HERE on a comment, in JS. I will personally convert to TSX, also here. You can then update and submit the PR)

---

- [x] The Wrapper component will nest `children`
- [x] It will hold all the MAIN components of the app, semantic HTML counts here =)
- [x] Its requirements are height of 85vh and width of 100vw
- [x] Export default and import in `App.tsx`
- [x] It will wrap the main content between `Header` and `Footer`
- [x] Add any element with some mock text in between the wrapper for now

```
<Wrapper><p>This is some mock text</p></Wrapper>
```

---

If willing to take on this task, please comment below to be assigned to it, read the contributing.md, and remember to submit PRs to development branch.

Thank you and happy collab!

**Comment by TN2812** [comment]
Hi, I want to solve this issue, please!
