### ISSUE TITLE
New Component: NavLogged file structure - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#19]
> ATTENTION: No Coding skills needed =)

---

With the Nav being currently worked on, we will now create the structure for a nav that will show if the user is Logged in. To prepare for that, we need the file structure:

---

- [x] In the components folder, found in client/src, Create a new Directory called `NavLogged`
- [x] NavLogged will have two files,` NavLogged.tsx` and `NavLogged.module.css`
- [x] In `NavLogged.tsx` import `classes` from the cdd module
- [x] hint: Check other components to see how to import the module

---

If willing to take on this task, please comment below to be assigned. Read the contributing.md file and remember to always PULL development and open PRs also to development branch. 

Thank you and happy Collab!

**Comment by KatarinaChavkova** [comment]
Hi, can be this issue assigned to me?

**Comment by Medic1111** [comment]
Absolutely! All yours =)
Have fun and please remember to read contributing.md, and Open PRS to the development branch
Happy Collab!
