### ISSUE TITLE
New Component: Portal: JSX/TSX - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#25]
> Now that we have a new div on html, we will use it to create a Portal. If you know how to create portals in React, feel free to collab. If you don't know TS, no worries, comment the solution in JS below, and Ill add what's needed for the TS conversion so you can commit.

---

- [x] Inside client/src create a Directory called `Portal`
- [x] Inside `Portal`, nest two files: `Portal.tsx` and `Portal.module.css`
- [x] The element to bind to is has an ID of `portal`
- [x] For the wrapper, you can use an `article`
- [x] Assign a higher `z-index` to it.
- [x] Feel free to test it as you would like, just please remove all testing related code when done

---

If you feel like you can take on this task (even if partially), please comment below to be assigned. Remember to read the contributing.md file and Open PRs to the `development` branch. 

Thank you and happy collab! =)

**Comment by aruadecarvalho** [comment]
Hi! Can I work on this issue?
