### ISSUE TITLE
New Component: Modal File Structure- Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#26]
> ATTENTION: No coding knowledge needed.

---
- [ ] In client/src/component, create a new Directory called `Modal`
- [ ] Nest two files within modal: `Modal.tsx` and `Modal.module.css`
- [ ] `Modal.tsx` will import `classes` from the css module
- [ ] Hint: Check other components to see how to import a css module

---

If you feel like you can take on this task, please comment below to be assigned to it. Remember to read contributing.md and open PRs to the `development` branch.

Thanks and happy collab =)

**Comment by aruadecarvalho** [comment]
Thank you! I'll take a look on some other issues.

**Comment by Medic1111** [comment]
> Thank you! I'll take a look on some other issues.

If you dont find anything today, Im updating the list later tonight, so please check again tomorrow. =) Still LOTS to do here

**Comment by aruadecarvalho** [comment]
I see, I'd love to contribute more, I just need to learn some typescript first! I'd like to ask you for some advices about github and coding in general, is there a way that we can chat? If you're available of course.

**Comment by Medic1111** [comment]
> I see, I'd love to contribute more, I just need to learn some typescript first! I'd like to ask you for some advices about github and coding in general, is there a way that we can chat? If you're available of course.
For sure! =) https://discord.gg/zvaxdSwj
