### ISSUE TITLE
New Component: Why file structure - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#28]
> ATTENTION: No coding knowledge needed.

---
- [x] In client/src/component, create a new Directory called `Why`
- [x] Nest two files within modal: `Why.tsx` and `Why.module.css`
- [x] `Why.tsx` will import `classes` from the css module
- [x] Hint: Check other components to see how to import a css module

---

If you feel like you can take on this task, please comment below to be assigned to it. Remember to read contributing.md and open PRs to the `development` branch.

Thanks and happy collab =)

**Comment by AdityaNarayan2000** [comment]
Hey, I think I can start up with this task. Please assign it to me.

**Comment by Medic1111** [comment]
You got it! Its yours. Please, though, when opening a PR do it to the development branch, not the main =)
Happy collab

**Comment by Medic1111** [comment]
Also make sure to PULL development often as the code changes often =)

**Comment by Medic1111** [comment]
@AdityaNarayan2000 Please pull development and check the top contributors page where from github API you are featured. Let me know if you're okay with your image there. Ill make sure to add that disclosure on the contributing.md.
Let me know. Thank you.
