### ISSUE TITLE
New Component: Collab File Structure - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#29]
> ATTENTION: No coding knowledge needed.

---
- [x] In client/src/component, create a new Directory called `Collab`
- [x] Nest two files within modal: `Collab.tsx` and `Collab.module.css`
- [x] `Collab.tsx` will import `classes` from the css module
- [x] Hint: Check other components to see how to import a css module

---

If you feel like you can take on this task, please comment below to be assigned to it. Remember to read contributing.md and open PRs to the `development` branch.

Thanks and happy collab =)

**Comment by B1910668-TN** [comment]
Hi, I want to solve this issue. Can you assign me? Thanks! =)

**Comment by Medic1111** [comment]
Hello and Thank you. Absolutely... It's yours. Please ensure to read contributing.md and remember to open PRs to `development` branch =)

**Comment by Medic1111** [comment]
Just to let you know, There was a mistake on MY PART. The directory name is not `Modal` but rather `Collab`.
If you can rename it before merge that would be awesome. You contribution helped more than you expected bc I was able to catch that same exact error on two other issues! THANKS MUCH!
