### ISSUE TITLE
File Edit: Roster - Good first issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#41]
> The roster is supposed to have one set style, which is what you see in the first two entries.

- [ ] Fix the style of the following collaborator's cards to match the standard

If you feel like you can help, please comment below, read the contributing.md and open PRs to the development branch

Thank you and happy Collab

**Comment by Matthew-Mu** [comment]
Hi there, can I have this one? I'm guessing you want the extra separator removed and the email fixed up?

**Comment by Medic1111** [comment]
@Matthew-Mu ABsolutely =) 
Thank you so much! Please open PRs to DEV branch
