### ISSUE TITLE
Update README - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#5]
# Running Locally

> The readme section responsible for explaining the steps needed to run this project locally, is rather advanced for some devs that are JUST starting. 

> With that in mind, and very detailed step by step contribution would be DOPE! And help a lot!

---

- [ ] Remove old "RUNNING IT" section of README
- [ ] Add new, well structured, list style, step by step on:
- [ ] How to FORK it
- [ ] How to install dependencies client
- [ ] How to install dependencies server
- [ ] How to run the client
- [ ] How to run the server

---

Anyone willing to help, please comment below to be assigned.

**Comment by Cngsu** [comment]
Hello @Medic1111 I want to participate in editing and solving this issues. Can you accept this request? Thanks!

**Comment by Cngsu** [comment]
I completed the issue and made a pull request to merge into the DEVELOPMENT branch as requested. Hope this helps, nice to work with you.

**Comment by Medic1111** [comment]
Great job! Thank you so much for your contribution. MERGED.
