### ISSUE TITLE
NavigationStates interface - Good first issue 

### ISSUE THREAD

**Issue by aruadecarvalho** [Medic1111/FINALLY-SEEN#52]
![image](https://user-images.githubusercontent.com/103606795/203074020-c0a1c80a-d729-47e9-8718-8b03abd78e09.png)

## To do:

- [ ]  Create a new file in client/src/models
- [ ] Name it NavigationStates.tsx
- [ ] Create and export an interface with the respectives props (setShowNav, setShowModal, setIsLoggin) being passed in the components (Nav, Header and Hamburguer)
- [ ] Import the interface in the components and do the necessary changes

#### any questions or difficulties, please paste here so you can get help =)

If you want to take this task please comment below to be assigned, read the contributing.md and open PRs to the development branch.

Thanks and happy Collab!

**Comment by Generatores** [comment]
Hi,

I can take care of this issue, please assign it to me

**Comment by Generatores** [comment]
I see that the ButtonBox component has 2 of the 3 props to be created on the new interface,

Will be ok for you to create an interface with this 2 props and extend it for the 3 props interface requested?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/77598237/205118105-7a931291-080f-412c-ba74-089d53e09e1a.png">

**Comment by aruadecarvalho** [comment]
Go for it!

**Comment by Generatores** [comment]
Hi,
Just created the pull request but dont know how to link it to the issue

**Comment by aruadecarvalho** [comment]
@Generatores  Good job! Thank you for the collab. Feel free to take a look at the other issues :) !
