### ISSUE TITLE
HTML: Link LEARN MORE CTA to WHY section. Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#58]
> Skills needed: HTML

---

Currently the CTA that read LEARN MORE does nothing. Have it redirect the section WHY of the main page.
Hint: WHY section already has an ID

If you think you can help, please comment bellow and I will assign you the task. Read the contributing.md and most importantly happy collab!
ps: open PRs to the development branch only. 

Thank you! =)

**Comment by was-coder** [comment]
Do I have this issue assigned to me now @Medic1111 ?

**Comment by Medic1111** [comment]
Its yours!
Thanks MUCH

**Comment by was-coder** [comment]
ok, Thanks

**Comment by was-coder** [comment]
We can close this issue @Medic1111
