### ISSUE TITLE
HTML: Footer Logo to redirect to the top of the page- Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#59]
> Skills Needed: HTML

---

On the footer of the page, There's a logo FS. Have that logo, when clicked, redirect to the top of the page:
Hint: Neither the Nav nor the Hero has an ID.

If you think you can help, please comment bellow and I will assign you the task. Read the contributing.md and most importantly happy collab!
ps: open PRs to the development branch only. 

Thank you! =)

**Comment by was-coder** [comment]
Hi @Medic1111 , can I be assigned this task?

**Comment by Steentoons** [comment]
Hello @Medic1111, I have been looking for an excellent place to start my first open-source contribution. Would you mind assigning me the task?

**Comment by Medic1111** [comment]
@Steentoons Welcome and Its a pleasure to have your support! Would you be able to take on a similar task #58 ? Its the same logic, just in a different element.

**Comment by Medic1111** [comment]
Let me know, otherwise I can ask @was-coder to take on #58

**Comment by Medic1111** [comment]
Actually, @Steentoons I see you have opened a PR. So ill ask @was-coder to take on #58 instead. Thank you both for the support =)

**Comment by was-coder** [comment]
ok @Medic1111

**Comment by Medic1111** [comment]
Thanks MUCH @was-coder
