### ISSUE TITLE
Update CONTRIBUTING.md - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#6]
> The idea is to have a section in there for total beginners, explaining how the contribution process works when it comes to git workflow.

---

- [x] Create section with instructions on:
- [x] how to fork and run it
- [x] how to create a new branch
- [x] how to push their branch
- [x] how to open a PR to development

---

Those steps can be really scary for beginners and a times be what account for them NOT collaborating. To counter that and give them a chance at contributing, this section would be DOPE.

If interested in helping, please comment below to be assigned for this issue

**Comment by priya1011** [comment]
Can I work on it?

**Comment by Medic1111** [comment]
MERGED. Thank you so much for your contribution! =)
