### ISSUE TITLE
No Coding Skills Needed: Change a word - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#60]
The hero section has text that reads the word: collaboration. Change that to: contribution =)

If you think you can help, please comment bellow and I will assign you the task. Read the contributing.md and most importantly happy collab!
ps: open PRs to the development branch only. 

Thank you! =)

**Comment by yashkc2025** [comment]
I want to contribute.

**Comment by Medic1111** [comment]
All yours. And thank you! :)
