### ISSUE TITLE
Tailwind Padding: Add padding to Mobile view component- Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#61]
> Skills needed: Know how to add padding to mobile breakpoint with tailwind

The login and Register form, both need some LIGHT padding on mobile view

If you think you can help, please comment bellow and I will assign you the task. Read the contributing.md and most importantly happy collab!
ps: open PRs to the development branch only. 

Thank you! =)

**Comment by was-coder** [comment]
Hi @Medic1111 , can I be assigned this issue?

**Comment by Medic1111** [comment]
All yours! =) Have fun
