### ISSUE TITLE
Fix Lint Error: No Coding Skills Needed - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#69]
When you first open the project in the Browser, if you check the console you will see several Lint Errors.

> Ex:
Warning: Invalid DOM property `clip-rule`. Did you mean `clipRule`?

If you continue to read, it will also map you to the element's location. Find the element and fix the error by using the `did you mean` property.

---

If you think you can take on this task, please comment below to be assigned to it. Read the contributing.md file and open PRs to the DEVELOPMENT branch, not main. 

Thank you and happy Collab! =)

**Comment by valanm22** [comment]
Shall I work on this?

**Comment by Medic1111** [comment]
@valanm22 Its all yours! =) 
Please read contributing.md 
If you need help or have any questions, add them here. 
Thank you and Happy Collab!!!!
