### ISSUE TITLE
Change Paragraph Color: Hero component - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#70]
The hero component has a paragraph that's currently very light in color. Although its okay in large and medium screens, please observe it in mobile view. It is unreadable.

---

Task: Change the color of the paragraph to darker so it's accessible. Attention: change ONLY on mobile view.

If you think you can help with this task, please comment below to be assigned. Read contributing.md and open PRs to the DEVELOPMENT branch. Not main.

Thank you and happy collab! =)

**Comment by seiji327** [comment]
Hello!

May I work on this issue? 

If so, should it be the darker color of the one that is there (teal color) or should it be a different color such as grey or black?

Thank you.

**Comment by Medic1111** [comment]
@seiji327 All yours =)
I think of one of the dark tones we are currently working with. Ill let you make that decision =) 
Thanks and happy collab!

**Comment by seiji327** [comment]
@Medic1111 Thanks!

While I was working on the issue, I did realize that the text is not centered in the range of approximately 639px ~ 540px screen width (screen shot below). 


![Screen Shot 2022-11-29 at 12 59 39 PM](https://user-images.githubusercontent.com/110354126/204647843-1575e41b-b574-4b95-9136-70f79edc9081.png)


Would it be okay to add the fix of this to the PR or would you be opening a new issue?

**Comment by Medic1111** [comment]
Oh please center it! Nice Catch and great job! Thank you so much!
