### ISSUE TITLE
Let me in!: React props and onClick - Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#71]
The Hero's CTA that reads "Let me in" currently does nothing.

---

- [ ] Make it so when clicked, the Modal will show up
- [ ] Hint: You will need `setShowModal`
- [ ] The modal will likely render the Login form, we want the register instead.
- [ ] Hint: You will need `setIsLoggin`

---

If you think you can help with these tasks, please comment below to be assigned to them. Read the contributing.md file and Open PRs to the DEVELOPMENT branch, not main. 

Thank you and Happy Collab! =)

**Comment by Medic1111** [comment]
@Steentoons Its all yours =) 
Thank you and Have fun!

**Comment by Steentoons** [comment]
Thanks
