### ISSUE TITLE
New Component: NAV file structure- Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#8]
### ATTENTION: no TypeScript or Javascript knowledge needed for this task. =)

> The app will have a Nav bar nested in the Header component. For first contribution step, We will structure files to prepare for the Component.

---

- [x] Create a new Directory inside `components` called `Nav`
- [x] Within Nav, create two files: `Nav.tsx` and `Nav.module.css`
- [x] The `Nav.tsx` will import `classes` from `Nav.module.css`

---

> Hint: Check the other components if unsure how to import the css module

If you're willing to collaborate, please read CONTRIBUTING.md, and comment below to be assigned to this task. Please, open PRs to development branch.
Thank you and happy collabing!

**Comment by priya1011** [comment]
Please assign.

**Comment by Medic1111** [comment]
You're on! =)
