### ISSUE TITLE
Portal: HTML- Good first issue

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/FINALLY-SEEN#9]
### Attention: This task requires only HTML skills.

> In assumption that a modal will be used, we will bind such modal in a Portal. To prepare for that, we need a new node element on html.
---

- [x] In the `index.html` found in the `public` folder, create a new `div` element
- [x] Place the `div` above the existing div with id of root
- [x] Give it an id of `portal`

---

If interested in collaborating to this task, please comment below to be assigned to it. Read the contributing.md file and open PRs to the development branch.
Thanks and happy collabing!

**Comment by Cngsu** [comment]
Hi @Medic1111 I want to solve this issue and you can assign me. Thanks!

**Comment by Medic1111** [comment]
You're on! =)

**Comment by Medic1111** [comment]
Awesome! Thank you 🙏🏼😁
